"""add telegram fields to user

Revision ID: b1fd8a7c7a5a
Revises: 
Create Date: 2025-12-08 17:55:34.816444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fd8a7c7a5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('telegram_link_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('receive_alerts', sa.Boolean(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_user_telegram_chat_id'), 'user', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_user_telegram_link_token'), 'user', ['telegram_link_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_link_token'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_chat_id'), table_name='user')
    op.drop_column('user', 'receive_alerts')
    op.drop_column('user', 'telegram_link_token')
    op.drop_column('user', 'telegram_chat_id')
    # ### end Alembic commands ###
